stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

#link-check:
#  stage: test
#  image: chrisshort/awesome_bot
#  before_script:
#    - rm ab-results-*
#  script:
#    - awesome_bot --allow-redirect --skip-save-results 

compile:
  stage: test
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo

build-preview:
  stage: build
  environment:
    name: preview
    url: preview.devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 10d
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
#    - rm -rf public || exit 0
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
  script:
    - hugo --buildDrafts --buildFuture --config config.preview.toml
  except:
    - master

build-production:
  stage: build
  environment:
    name: production
    url: devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 10d
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
#    - rm -rf public || exit 0
#    - git submodule sync --recursive
#    - git submodule update --init --recursive
  script:
    - hugo
  only:
    - master

deploy-preview:
  stage: deploy
  environment:
    name: preview
    url: preview.devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://preview.${CI_PROJECT_NAME}/
  after_script:
    - bin/cf_purge.sh
  except:
    - master

deploy-production:
  stage: deploy
  environment:
    name: production
    url: devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://${CI_PROJECT_NAME}/
  after_script:
    - bin/cf_purge.sh
  only:
    - master