stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-preview:
  stage: build
  environment:
    name: preview
    url: https://preview.${CI_PROJECT_NAME}
  artifacts:
    paths:
      - public
    expire_in: 1d
  image: registry.gitlab.com/pages/hugo:0.56.3
  before_script:
    - apk --no-cache update
    - rm -rf public || exit 0
  script:
    - hugo -DF --config config.preview.toml
  except:
    - master

build-production:
  stage: build
  environment:
    name: production
    url: https://${CI_PROJECT_NAME}
  artifacts:
    paths:
      - public
    expire_in: 3d
  image: registry.gitlab.com/pages/hugo:0.56.3
  before_script:
    - apk --no-cache update
    - rm -rf public || exit 0
  script:
    - hugo --minify --config config.toml
  only:
    - master

deploy-preview:
  stage: deploy
  environment:
    name: preview
    url: https://preview.${CI_PROJECT_NAME}
  image: quay.io/chrisshort/firebase:latest
  before_script:
    - curl -L -o firebase.json https://raw.githubusercontent.com/chris-short/firebase-configs/master/firebase.preview.json
    - curl -L -o .firebaserc https://raw.githubusercontent.com/chris-short/firebase-configs/master/firebaserc.json
    - sed -i "s/REPLACEME/${FIREBASE_PROJECT}-preview/g" .firebaserc
  script:
    - firebase deploy --only hosting --token ${FIREBASE_TOKEN}
  except:
    - master

deploy-production:
  stage: deploy
  environment:
    name: production
    url: https://${CI_PROJECT_NAME}
  image: quay.io/chrisshort/firebase:latest
  before_script:
    - curl -L -o firebase.json https://raw.githubusercontent.com/chris-short/firebase-configs/master/devopsish.com/firebase.json
    - curl -L -o .firebaserc https://raw.githubusercontent.com/chris-short/firebase-configs/master/firebaserc.json
    - sed -i "s/REPLACEME/${FIREBASE_PROJECT}/g" .firebaserc
  script:
    - firebase deploy --only hosting --token ${FIREBASE_TOKEN}
  only:
    - master