stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

compile:
  stage: test
  image: registry.gitlab.com/pages/hugo:latest
  retry: 2
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --buildDrafts --buildFuture --minify

build-preview:
  stage: build
  environment:
    name: preview
    url: https://preview.devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 30m
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --buildDrafts --buildFuture --config config.preview.toml
  except:
    - master

build-gcs:
  stage: build
  environment:
    name: gcs
    url: https://devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 30m
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --minify
  only:
    - master

build-oss:
  stage: build
  environment:
    name: oss
    url: https://build.devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 30m
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --minify --config config.oss.toml
  only:
    - master

deploy-preview:
  stage: deploy
  environment:
    name: preview
    url: https://preview.devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://preview.${CI_PROJECT_NAME}/
  after_script:
    - bin/cf_purge.sh
  except:
    - master

deploy-gcs:
  stage: deploy
  environment:
    name: gcs
    url: https://devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://${CI_PROJECT_NAME}/
  after_script:
    - bin/cf_purge.sh
  only:
    - master

deploy-oss:
  stage: deploy
  environment:
    name: oss
    url: https://blocked.devopsish.com
  image: quay.io/chrisshort/ossutil:latest
  script:
    - ossutil -e ${OSS_ENDPOINT} -i ${OSS_KEY} -k ${OSS_SECRET} cp -j 8 -u -r public oss://${OSS_BUCKET}/
  only:
    - master