stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-preview:
  stage: build
  environment:
    name: preview
    url: https://preview.devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 30m
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --buildDrafts --buildFuture --config config.preview.toml
  except:
    - master

build-prod:
  stage: build
  environment:
    name: prod
    url: https://devopsish.com
  artifacts:
    paths:
      - public
    expire_in: 30m
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --minify --config config.toml
  only:
    - master

deploy-preview:
  stage: deploy
  environment:
    name: preview
    url: https://preview.devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://preview.${CI_PROJECT_NAME}/
  except:
    - master

deploy-prod:
  stage: deploy
  environment:
    name: prod
    url: https://devopsish.com
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://${CI_PROJECT_NAME}/
  after_script:
    - bin/cf_purge.sh
  only:
    - master