branches:
  only:
  - master
notifications:
  email: true
  pushover:
    api_key:
      secure: ZdbhprZHkb4qEZMXW8b0p8KN4Inqjlnl224mJioKjTSbjuFCKn4DbTYDULGQwu2AlGoF54myA7aLIZB34rZnti3rGJqMk6dZ3SwNWKSpH+RQWPkefQSoaXmpJAcQEgcWrEG3zvsvRLwQONur/o8j3xLWifX20nR7nILnf6CUqACAYZV+1xj1Wyj04QiAsksWwl4NKDepj95dp0/4Mw+WSONgGISt+KmcDWWZxKsSG7IjfSCVc8Z9zpLVeM+xQ7Ls05wDZnA1TE8oc4NoKl+KBZj9sAz9uuA6Floh1U0aSO40A1uCndhUG9N6QTM8kRMHN2gpA/Al3h8qQnwpxwJOrP4OLr0Et+ckuK/yIn7sYNfGP9he9kv0ksHFVRJKoywE9ixYl4BjbEhWlLKnyUVhIacmgU1uFwJCMyWNtqt4RXgp+VK4mfpnVo8m0NzYa9s1BDukyi0NEv6F7Fzhkd1p2x/lODx9i08BuJHgRUjzb9ipIH7DsPlJCny3mdOTPLPcihOEGlOwWhqPHJ/pTCFxJb6oE3/xaxPyLP1st7ovjeWceBZzy69dSaUnaIgNxH9XQrSYnSjVTZDwiqX7pjIh/vIDFWV/XT2zmXIJsjfnMZI5f3uMX99yvOC8+1T7+drFTi72SuuoehxrVSSoSf1MrJ4bkxzwd5l7Kt4bE3uxsh8=
    users:
      secure: VFQRrT8+B6YI1Zfr6TJZPITEk3aZQUM2+oObYyxc5zr3qQs2MuZNCyTNeLofQNryYeY0RQ7cy0yrX3qg2qNo83lniqpX6Dk8JfeAlxE8Xfdm/7rcNfKOi5YPOiucDC7gHMp44XBgYdBbrUjs0PPwYx7vxPlhL7tV+GQGCkD0mpmKESLMwPP6a7YV5jTAeXuP6NbyBvl72mqcuQf+u5LVzx6BgQPhvn5ZuEm8sskSp0mm0Wukupv/B7ZEI5Bh/ZnLZqtCJ2Jb29Xz+pr3Plw65nfemSsySsAVyuXJGqdWbj5o7ZcL3q7tzVc4Lk68XBHK0VSkkFGRJxfbF1M3nO4OQO+8lfeGK+FgyheSA0knk1LUAhIZnROhu/LDOaQktRSx4Jezi/yVgtgP9k6kozfU4FGGXwaPUVchHbcmjXd2O4k7VbhBjjSYS0TCM+sdibjIwxStCyYYqwvoCE5zESsPqKjLq4yKp2TqTTRGCM1OFIWEEsjzpbbXPAaG4IB/Ut1omw/YnnuU7IUSQH3U2RpHC37cxWOnnHv8DgFgo/9KviLG7RnDkU/52ozb+nV0Y68JPnS/W+8pX7CWdGZ0YxxVp/rtAC30qn+dNV3nH+mX5Ijb3lZDAFLkxa6qA2Iq4Sz6173+O6lWHpBFhqFhFpFSVQKe7OhnYDpEK8Obv807G6w=
cache: false
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
before_script:
- curl --silent -L https://github.com/gohugoio/hugo/releases/download/v0.35/hugo_0.35_Linux-64bit.tar.gz
  | tar zxf -
script:
- GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse
  --short HEAD` ./hugo
deploy:
- provider: gcs
  access_key_id: GOOGU2LT7AP6FT66C6RA
  secret_access_key:
    secure: fN6CoxBEAHN1ruGc8Spm7qbygt5gfMguYh3kseg0O6wI/BZ8zOw7n4+s1K0m/oTywMMCVzz6qG+3padhl36dXJ5Ua9tg1NsCbBoPsBIPAFMxsKII20CITAY4KapLCG1fB66F0zwt1ftdgiKZjxgl/tTZ0zjzP4iRSAurOhnqhv8ulLMaJZJMDeSXddgytwIJeZp76I6911d6N/nqADEeyCUwxmI4fN9vEphJaKnh6vrSUFw/43h0Cz8MEy6RzPLY+uDnfX4fkIbnrdiV7PTh81yOwpF0QZ0id3IIiciAYSeGfXlYXxLDlCY1aLmvy90k9UvceLddXJ8ekCZvEOUwpiaGlcX5APvpawL4u4iZxKfPg7ttO75Hi7qxQtYVDztcUBbKu7BkJlHuarjCYji1D7q7BMnAhjCbrpVDxd+JUZmeJ+2tVV/kSUTXAK9ESDUODNyDuHYPPmX6T0elxmIqgQVP8QSt0Yf2LmSHpz/2/MGEzJ2Qr4cCJWyd2f8wuRatboKHB6oIXROBWuuxOiIPhc6/kWqQsIvuq0UEUtWghzDodcA/XQvYQ/x+XSm6lQTJpZrr4z+udevzkwo4+J8z8FV3rnP2Xb8kKOxiC/xygiLfzN4xrKdKgyWE1KraBfxIaLh/OnkfQvpEDYksAIQ7qpV1ExvBS68Y2I7jsGPKm58=
  bucket: devopsmeh.com
  local-dir: public
  skip_cleanup: true
  acl: public-read
  on:
    repo: chris-short/devopsish.com
    branch: master