baseURL = "https://preview.devopsish.com/"
copyright = "[Some rights reserved](https://devopsish.com/cc-by-sa-4.0/) | [Terms](https://devopsish.com/terms/) | [Privacy](https://devopsish.com/privacy/) | [What is DevOps](https://devopsish.com/what-is-devops/)"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-4498776-13"
languageCode = "en-us"
metaDataFormat = "toml"
newContentEditor = "code"
paginate = 6
relativeURLs = true
rssLimit = 5
theme = "hugo-theme-bootstrap4-blog"
title = "DevOps'ish PREVIEW"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = ":slug/"
  page = ":slug/"

[params]
  author = "Chris Short"
  description = "DevOps, Cloud Native, Open Source, and the 'ish between."
  favicon = "/favicons/favicon.ico"
  disable_sri = true

  [params.sidebar]
    About = "DevOps'ish is a weekly newsletter assembled by open source contributor, DevOps veteran, and CNCF Ambassador [Chris Short](https://chrisshort.net/)."
    num_recent_posts = 6

  [params.stats]
    subscribers = "2,916"
    avg_open_rate = "48.1%"
    avg_click_rate = "22.7%"

[Author]
  name = "Chris Short"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = false